package:
  name: batchconvert
  version: 0.0.4

source:
  git_url: https://github.com/Euro-BioImaging/BatchConvert.git
  git_tag: conda_version_dev_mini

build:
  number: 0

requirements:
  build:
    - python>=3.9
  host:
    - python>=3.9
  run:
    - conda-forge::python>=3.9
    - bioconda::nextflow>=23.10.1
