#!/usr/bin/env bash

condapath=$( which conda );
while ! ls -a $condapath | grep etc &> /dev/null;
do
  if ls -a $condapath | grep etc &> /dev/null; then
    hhh="blabla"
  else
    condapath=$(dirname $condapath)
  fi
done

source $condapath/etc/profile.d/conda.sh && \
conda activate nflow && \
nextflow "$@"
