name: batchconvert
channels:
  - ome
  - conda-forge
  - joshmoore
  - defaults
  - hcc
dependencies:
  - python ~= 3.9.0
  - bioformats2raw
  - bftools
  - go-mc
  - aspera-cli
  - pip
  - pip:
    - git+https://github.com/Euro-BioImaging/ome_zarr_pyramid.git
